### ISSUE TITLE
Should create an app.min.js file

### ISSUE THREAD

**Issue by rochamarcelo** [justcoded/web-starter-kit#117]
After executing gulp build I would expect to have a app.min.js file. I don't see a reason to not create a minified file for js.

**Comment by sgurin** [comment]
Hi, @rochamarcelo 

Thanks for the feedback.

We do not minify or/and uglify app.js file because that file includes only custom JS that in 90 % consist of init functions. So, in case of errors we can easily debug.

**Comment by sgurin** [comment]
Added in #118
