### ISSUE TITLE
How to import modules installed through npm?

### ISSUE THREAD

**Issue by stonecauldron** [justcoded/web-starter-kit#47]
Hello,

First thank you for maintaining this excellent repo, it really is a huge time-saver.

I have a question:

How can I import external modules that were installed through npm?

The `README` mentions that we should include them into the `src/js/vendor.js` file. But how do we actually import these external modules in the `app.js` file? Let us say I want to import `lodash` in `app.js`. How would I proceed?

The `vendor.js` file also mentions that ES6 support for these imports is not supported in the base build; what does this mean concretely? That we cannot use the ES6 import syntax for modules installed through npm?

**Comment by KirillPd** [comment]
Hi @stonecauldron,

Thank you for the feedback.

1. You can import external modules in the `src/js/vendors.js` file ([example](https://github.com/justcoded/web-starter-kit/blob/master/src/vendor_entries/vendor.js)) and then you’re free to use them in your `app.js` file.

2. It means that external modules which were written using ES6 syntax won’t be transpilled to ES5 syntax.

**Comment by stonecauldron** [comment]
@KirillPd Thank you for your quick reply.

1. I had followed the example and included an external module in `src/js/vendor.js` my question was about how to use the module in the `app.js` (and others) file. Is it included in the global scope like the example with `jQuery` suggests? Or should I import it with the ES6 syntax? Sorry if this wasn't clear.

2. That makes sense, thank you.

**Comment by KirillPd** [comment]
@stonecauldron Definitely, you don't have to import it. If you add an external module to your `vendor.js` file, it is already in the global scope. So you're able to use `lodash`, `jquery` in your `*.js` files without any imports ([example](https://github.com/justcoded/web-starter-kit/blob/master/src/js/app.js)).

Hope, this time I answered your question 👍

**Comment by stonecauldron** [comment]
@KirillPd yes perfect, thank you for your time!
