### ISSUE TITLE
Issue with SVGO

### ISSUE THREAD

**Issue by sgurin** [justcoded/web-starter-kit#48]
Hi there.
I hope you are well, mate :)
I have a problem with SVG after web starter kit compressed this [capital-bg.svg.zip](https://github.com/justcoded/web-starter-kit/files/1604070/capital-bg.svg.zip) SVG.
Can you please take a look why it is happing.

**Comment by KirillPd** [comment]
Hey @sgurin,
I've just went trough this issue. I have no idea why `gulp-imagemin` breaks this image. However, after image processing in https://jakearchibald.github.io/svgomg/ everything is Okay. Maybe some of the unprocessed lines in the svg file cause this issue.

UPD. I updated the `gulp-imagemin` package and now it works as expected. Note that I updated this package only in the [gulp-4-refactoring](https://github.com/justcoded/web-starter-kit/commit/a7aeb616e1c239d50750a852a6a46d555621f720) branch.
