### ISSUE TITLE
Ability to add or remove SCSS

### ISSUE THREAD

**Issue by sgurin** [justcoded/web-starter-kit#55]
Please provide more flexible solution in your build for compiling separate SCSS files.

**Comment by KirillPd** [comment]
Hey @sgurin,
Now You're able to add your own custom sass files and optionally [don't apply gulp-group-css-media-queries module to them](https://github.com/justcoded/web-starter-kit/issues/56).

You can see this property in the gulp-config.js file:
![image](https://user-images.githubusercontent.com/14921077/36471272-8ce84fbc-16f6-11e8-8173-4e41d1dbbb9f.png)

Please don't forget to link all your custom sass files in html:
![image](https://user-images.githubusercontent.com/14921077/36471279-9387a368-16f6-11e8-9814-a7f1a18150fc.png)

Also, you might want to add these sass files to the ignore list (check getPathesToCopyForProduction and getPathesToCopy properties in the gulp-config.js file). By default they will be copied to the assets and production folders.

**Comment by KirillPd** [comment]
I've [updated](https://github.com/justcoded/web-starter-kit#scss) the readme docs according to this update
