### ISSUE TITLE
gulp-group-css-media-queries issues

### ISSUE THREAD

**Issue by sgurin** [justcoded/web-starter-kit#56]
Hi, bro. gulp-group-css-media-queries does not working correct with media queries which included height media queries.
Here is a SCSS code:
@include media("<phone", "height<737px") {
.home & {
min-height: 320px;
}
Add a comment to this line
}
@include media("<phone", "height<700px") {
.home & {
min-height: 270px;
}
}
@include media("<phone", "height<635px") {
.home & {
min-height: 260px;
}
}
@include media("<phone", "height<622px") {
.home & {
min-height: 250px;
}
}
@include media("<phone", "height<604px") {
.home & {
min-height: 245px;
}
}
@include media("<phone", "height<600px") {
.home & {
min-height: 215px;
}
}
@include media("<phone-small", "height<500px") {
.home & {
min-height: 180px;
}
}

And this is a result http://prntscr.com/ifmcxs with wrong chain of queries

**Comment by KirillPd** [comment]
Hey @sgurin,
Unfortunately, it is an issue with `gulp-group-css-media-queries` itself. We did a temporary hacky workaround for this case.
Now You're able to add your own custom sass files and don't apply `gulp-group-css-media-queries` module to them.

You can see this property in the `gulp-config.js` file:
![image](https://user-images.githubusercontent.com/14921077/36470934-4f0864da-16f5-11e8-91c8-b996515e0ae4.png)

Please don't forget to link all your custom sass files in html:
![image](https://user-images.githubusercontent.com/14921077/36470996-88d2d4d4-16f5-11e8-936c-2dd4bdd8b83e.png)

Also, you might want to add these sass files to the ignore list (check `getPathesToCopyForProduction` and `getPathesToCopy` properties in the `gulp-config.js` file). By default they will be copied to the assets and production folders.
