### ISSUE TITLE
problems with "templates" task 

### ISSUE THREAD

**Issue by JulianVera** [justcoded/web-starter-kit#58]
Hi!
I followed the instructions to install the WSK and i can't see in my project the "templates" folder when i use  "gulp production". And in the tasks folder it doesn't appear. What i'm can be doing wrong?

**Comment by KirillPd** [comment]
Hey!
We have a few versions of WSK. One of them uses pug. Probably you downloaded the default version which isn't support pug.

I advise you to use this [tool](https://github.com/justcoded/npm-jcn) for projects init. This command line tool allows you to install right configuration without any problems.

![image](https://user-images.githubusercontent.com/14921077/37019756-325e9f16-2122-11e8-83f2-163af96f8108.png)

**Comment by JulianVera** [comment]
This goes beyond, excelent weapon my friend- saved me a lot of time, i installed the CL tool and it worked perfect! thanks for this work.

**Comment by KirillPd** [comment]
@JulianVera Thank you!
