### ISSUE TITLE
Can not add popper.js into vendor.js and unknown problem with bootstrap file

### ISSUE THREAD

**Issue by ngocsangyem** [justcoded/web-starter-kit#62]
there is an error with popper.js and bootstrap http://prntscr.com/j47hp9

**Comment by KirillPd** [comment]
Hey,
Thanks for the report!

1. **popper.js** I'm facing the same problem with `popper. Popper uses ES6 syntax in the `dist` files and `gulp-uglify` [doesn't support it](https://github.com/terinjokes/gulp-uglify/issues/300) :(

As temporary workaround you can comment this line in `build-js-vendors.js` task:
![image](https://user-images.githubusercontent.com/14921077/39073995-6d8f53b0-44f8-11e8-9509-654023a4aa02.png)

2. **bootstrap** I can't reproduce this issue. Installed bootstrap 4.1.0 and `gulp` works as expected.
