### ISSUE TITLE
Working with custom fonts

### ISSUE THREAD

**Issue by JulianVera** [justcoded/web-starter-kit#64]
Hello guys!

I-m trying to add some custom fonts to the project but i i'm kind of a rookie. What would we the best practice to work with custom fonts? I have to create a new task un gulp?

Cheers-

**Comment by KirillPd** [comment]
Hi @JulianVera,

Just create a `fonts` folder with your custom fonts and add them in `src/scss/base/_fonts.scss` using `@font-face`.

Here is an example:
![image](https://user-images.githubusercontent.com/14921077/39072544-886e9aba-44f3-11e8-88ae-25e1ccb97f03.png)

**UPD**
You can use only [woff2](https://caniuse.com/#feat=woff2) font format (and [woff](https://caniuse.com/#feat=woff) for IE)

**Comment by JulianVera** [comment]
Hi KirillPd!
Sorry for answering late, it worked perfect! I added the fonts and executed gulp, then the fonts were generated in the assets folder of the root site.

Thanks!
