### ISSUE TITLE
Bootstrap build issues

### ISSUE THREAD

**Issue by sgurin** [justcoded/web-starter-kit#66]
These files should not be in Bootstrap version of build even if they were not imported in the main.scss file http://prntscr.com/ja1zo9

**Comment by kpoddubnyi** [comment]
It's a [jcn](https://github.com/justcoded/npm-jcn) issue. 

The software implementation will be strongly related on folders/files structure  and it'll take a lot of time to solve such problems.
The only one option now is to delete these files manually after project configuration.

Anyway these files won't be copied to the sources folder, so I don't think that it's a real issue.
