### ISSUE TITLE
Jshint Bug 

### ISSUE THREAD

**Issue by ngocsangyem** [justcoded/web-starter-kit#68]
Hi , I use paginationjs [https://github.com/superRaytin/paginationjs](url) and it have a problem like this https://bit.ly/2HUFmA9

**Comment by kpoddubnyi** [comment]
Hi @sangsangg99,
Looks like your image url is dead

By the way, I installed `paginationjs` and added code parts from the readme. I don't see any errors from `jshint`.

Could you update the image link and provide more information about this issue?

**Comment by ngocsangyem** [comment]
Hi @kpoddubnyi ,
I haved updated the image link http://prntscr.com/jguqvv

**Comment by KirillPd** [comment]
Jshint says that you have some issues in the app.js file. Could you share it?

**Comment by ngocsangyem** [comment]
hi, i found out what happened to my app.js file .  i forgot to add the accent " ; " and i forgot the build tool use "use strict mode" . Thanks for your answer
