### ISSUE TITLE
@import warning

### ISSUE THREAD

**Issue by sgurin** [justcoded/web-starter-kit#69]
Hi, bro.
Take a look on this msg http://prntscr.com/jje81j Do we have any reasons to worry?

**Comment by kpoddubnyi** [comment]
Hi,
You do, in case if you include `.css` files with `@import`

**Comment by sgurin** [comment]
We need to fix it somehow cause there are a lot of plug-ins that has only CSS version.

**Comment by kpoddubnyi** [comment]
I've read this thread https://github.com/sass/node-sass/issues/2362 and as I see there is no appropriate option so far
