### ISSUE TITLE
Bootstrap variables in boots4 project

### ISSUE THREAD

**Issue by jjvera** [justcoded/web-starter-kit#72]
Hello!

I'm having problems when i define a project with Bootstrap 4 and try to use variables or mixins from the framework. Every time i call a variable or mixin it behave like i-m not loading the files, example:

>>   `Error: no mixin named media-breakpoint-down
        on line 16 of src/scss/components/nav.sass
        from line 21 of src/scss/style.min.css
 @include media-breakpoint-down(md) {

and the head is ok

>> head
  meta(charset='utf-8')
  meta(name='viewport', content='width=device-width, initial-scale=1.0')
  title Web Starter Kit
  link(media='all', rel='stylesheet', href='assets/css/vendor.min.css')
  link(media='all', rel='stylesheet', href='assets/css/style.min.css')

**Comment by KirillPd** [comment]
HI @jjvera,

Could you please send me a link to your repo?

**Comment by jjvera** [comment]
its in bitbucket, do you have an email? 

Thanks!

**Comment by KirillPd** [comment]
kpoddubnyi@justcoded.co

**Comment by kpoddubnyi** [comment]
btw, could you please try to add this bootstrap file with mixins here https://github.com/justcoded/web-starter-kit/blob/master/src/scss/style.scss ?

**Comment by jjvera** [comment]
Hello ! 

It worked perfect by calling the variables and mixins files right there:

`//* Vendors *//
@import './node_modules/include-media/dist/include-media';
@import './node_modules/bootstrap/scss/_functions.scss';
@import './node_modules/bootstrap/scss/_variables.scss';
@import './node_modules/bootstrap/scss/_mixins.scss';`

Thanks!

**Comment by KirillPd** [comment]
@jjvera 
Glad to hear! Could you please close the issue?
