### ISSUE TITLE
Using Js in html templates

### ISSUE THREAD

**Issue by JulianVera** [justcoded/web-starter-kit#73]
Hello!

I have a problem calling the js functions from the template html outside of app.js.

I created a function in app.js and when I call it at the end of the html (after the footer when the app.js and the providers are loaded) I receive an error in the console telling me that it is not defined.

`Uncaught ReferenceError: curtainOpen is not defined
    at (index):190`

What i-m missing?

**Comment by kpoddubnyi** [comment]
Ciao!

Maybe you didn't declare the `curtainOpen` variable?
Show me the code please.

**Comment by JulianVera** [comment]
In app.js

![image](https://user-images.githubusercontent.com/10487947/44049370-4d87ee76-9f0a-11e8-969a-0c4a13f6a7c5.png)


```
function curtainOpen(){
        var surveyCurtainLine = $('.curtain-transition line').toArray();
        TweenMax.set('.view-survey .curtain-transition', {display: 'block'});
        TweenMax.set(surveyCurtainLine, {opacity: 1, transformOrigin: "left"});
        surveyCurtainLine.sort(function(){return 0.5-Math.random()});
        TweenMax.staggerFromTo(surveyCurtainLine, 0.2, {display: 'block', scaleX: 1, ease: Power4.easeOut},{scaleX: 0, display:'none', ease: Power4.easeOut}, 0.025); 
        TweenMax.staggerFromTo('.view-survey .container .row', 0.3, {opacity: 0, y: 50},{opacity: 1, y: 0, delay: 0.8}, 0.2); 
        TweenMax.to('.curtain-transition', 0.001, {display: 'none', delay:'1.5'});
    };
```

Then, in the html

![image](https://user-images.githubusercontent.com/10487947/44049409-6174e632-9f0a-11e8-97b7-6763885b5804.png)

```
doctype html
html(lang='en')
	include ../partials/head
	body
		include ../partials/nav
		main.my-sm-5.my-4
			include ../partials/curtain-transition
			.container
				...
	include ../partials/foot
	script.
		setTimeout(function () {
		curtainOpen();
		}, 1300);
```

If i copy the timeout into app.js it works, that confuses me.

**Comment by kpoddubnyi** [comment]
Are you sure that you declared this `curtainOpen` function in global scope?

**Comment by JulianVera** [comment]
Yes, but it is in the app.js, that loads when DOM is ready and i'm inserting this script  at the end of the html, so i guess its loading before the app.js.

What is the best practice if i want to use a custom script in a specific view?

**Comment by kpoddubnyi** [comment]
I don't think that it's a good practice to write js code directly in html template. Why don't you create a new js file and import it in `app.js` file?

**Comment by JulianVera** [comment]
I want to call the functions inside app.js from another .js file, but i think app.js don-t allow you to scope for it

**Comment by kpoddubnyi** [comment]
Just import your js file in `app.js` and use the functions? Do you see my point?

**Comment by kpoddubnyi** [comment]
@JulianVera if you have any questions just write them here. I'm going to close this issue.
