### ISSUE TITLE
Remove use strict in js file

### ISSUE THREAD

**Issue by ngocsangyem** [justcoded/web-starter-kit#74]
Hi !
How can i remove use strict in js file ?

**Comment by kpoddubnyi** [comment]
Hi @sangsangg99,
I'm afraid that you have to fork this starter and delete it.
Are you sure that this is necessary?

**Comment by ngocsangyem** [comment]
Hi @kpoddubnyi  , 
Why i have to fork this starter , can you get more detail?

**Comment by kpoddubnyi** [comment]
@sangsangg99 just open this file and delete the 'use strict'; declaration https://github.com/justcoded/web-starter-kit/blob/master/src/js/app.js

**Comment by ngocsangyem** [comment]
@kpoddubnyi I have delete the 'use strict' in my app.js but it dont't work

**Comment by kpoddubnyi** [comment]
@sangsangg99 when you use es6 imports your code runs in the 'use strict' mode too. Why do you want to disable this?

**Comment by ngocsangyem** [comment]
@kpoddubnyi  Babel will help you build the 'use strict' , you don't have to use 'use strict' in dev mode

**Comment by kpoddubnyi** [comment]
Are we on the same page?
"Strict mode makes several changes to normal JavaScript semantics:

Eliminates some JavaScript silent errors by changing them to throw errors.
Fixes mistakes that make it difficult for JavaScript engines to perform optimizations: strict mode code can sometimes be made to run faster than identical code that's not strict mode.
Prohibits some syntax likely to be defined in future versions of ECMAScript."
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

Why should we disable it in dev mode?

**Comment by ngocsangyem** [comment]
I get it , thanks for your answer
