### ISSUE TITLE
Build js vendor problem

### ISSUE THREAD

**Issue by themeix** [justcoded/web-starter-kit#78]
Hello, 

I am facing issue to use it. 
Here following my vendor.js file 

```
module.exports = [
//  './node_modules/jquery/dist/jquery.js',
  './src/js/modules/jquery-3.3.1.min.js',
  './src/js/modules/bootstrap.min.js',
  './src/js/modules/easing-efect.js',
  './src/js/modules/fontawesome.min.js',
  './src/js/modules/highlight.pack.js',
  './src/js/modules/jquery.waypoints.min.js',
  './src/js/modules/menumaker.min.js',
  './src/js/modules/owl.carousel.min.js',
  './src/js/modules/prism.js',
  './src/js/modules/popper.js',
  './src/js/modules/responsive-menu.js',
  './src/js/modules/wow.min.js'
  ];
```
and app.js file 

```
// import DE from './modules/main';
(function ($) {
"use strict";
$(".open-nav").on("click",function(e){
	$("#myLinks").toggleClass("active");
	e.preventDefault();
})    
}); 
}(jQuery));
```
Unfortunately when i am running the command `gulp `or `gulp-dev` , getting the following error

```
✖ 61414 problems (59971 errors, 1443 warnings))
49170 errors and 0 warnings potentially fixable with the `--fix` option.
```
That error actually occurring when then **build-js-vendors.js** task starting 

Please tell me, how to fix that?

**Comment by KirillPd** [comment]
Hey,

Why don’t you install all dependencies using npm? I see that you’re using source folder as a vendor folder. Please avoid it and use node_modules instead.

**Comment by sgurin** [comment]
Hi.

Also you can add your plugins folder to .eslintignore file and ESlint will not validate these files.

**Comment by themeix** [comment]
Thanks for quick response.. .eslintignore helped. All the js plugins are not available in npm. That's make the problem.. So i used vendor.js to call these file from modules folder

**Comment by sgurin** [comment]
Hi.

You can use NPM for plugins such as jQuery  https://www.npmjs.com/package/jquery Bootstrap https://www.npmjs.com/search?q=Bootstra and so on. Almost every plugin you can find on https://www.npmjs.com. It is simple to use and you can control each of plugins version as well.
