### ISSUE TITLE
Minification error (Unexpected token: keyword (const)

### ISSUE THREAD

**Issue by themeix** [justcoded/web-starter-kit#79]
Getting the following error while using web starter kit. When i am commenting the ` .pipe(uglify())` from build-js-vendors.js then its working but is that only solution for that?

````
[03:51:22] 'build-js-vendors' errored after 7.18 s 
[03:51:22] GulpUglifyError: unable to minify JavaScript Caused by: SyntaxError: Unexpected token: keyword (const)
````

**Comment by KirillPd** [comment]
Hey @themeix,

Unfortunately, it's [a problem](https://stackoverflow.com/questions/47439067/uglifyjs-throws-unexpected-token-keyword-const-with-node-modules) with uglify itself.

**Comment by themeix** [comment]
Yes.. using your script by commenting **.pipe(uglify())**

**Comment by KirillPd** [comment]
Have you tried [gulp-uglify-es](https://gitlab.com/itayronen/gulp-uglify-es) instead of gulp-uglify?

Be aware that gulp-uglify-es is no longer maintained.

**Comment by themeix** [comment]
Yes.. tried and it does not help. No problem i am not using uglify anymore.. just using the minified soruce files
