### ISSUE TITLE
Copy Vendor CSS and JS files in dev command

### ISSUE THREAD

**Issue by themeix** [justcoded/web-starter-kit#80]
I really loved to use web starter kit but there i am facing an issue and i believe if it could be work then it would be awesome. 

while using gulp dev command, all the css and js file should be copy in assets foulders as it is not production version. So gulp dev command should copy the source files  and place on assets area. There vendor css and js file should be un-minified as well..

But while using gulp production then only the vendor css and js with minification format would be fine.

**Comment by KirillPd** [comment]
Hey @themeix,

Thanks for the feedback! 
So the problem is that `gulp dev` minifies files, right?

**Comment by themeix** [comment]
Yes and also we want all the resources in assets folder in dev command.
Eample : 
If i use the bootstrap from the node_module in vendor.scss file then we cant get the file in asset folder anyomore.. but if it can be copy and paste to the assets/css folder then it would be great for the developers who want to keep minified and unminified version separate.

**Comment by KirillPd** [comment]
I got you. cc @sgurin

**Comment by sgurin** [comment]
Hi, @thememix.

In that case you can copy the whole bootstrap folder into src folder and add import into vendrors.scss.

Assets folder generates from src every time when you make changes, so do not put anything into it. Otherwise it would be overwritten.
