### ISSUE TITLE
Unminified version of main stylesheet from SCSS

### ISSUE THREAD

**Issue by themeix** [justcoded/web-starter-kit#83]
How can we get the unminified version of the main stylesheet which generating from the scss file.  Because it always generating 2 minified css file ( vendor.min and style.min ). For example i want the un minified version of the style.css which generating form the scss.

For the themeforest project they do not allow minified css. It just needed for the demoing the html template for better optimization.

**Comment by sgurin** [comment]
Hi, @themeix 

You can comment these two pipes http://prntscr.com/n9ij9j tasks/build-styles-vendors.js and the same lines in the tasks/build-sass-production.js

After that you will need to re-run gulp
